package ServoConRemote.IScopeChannelPackage;

/**
* ServoConRemote/IScopeChannelPackage/_s_dataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class _s_dataHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IScopeChannelPackage._s_data value = null;

  public _s_dataHolder ()
  {
  }

  public _s_dataHolder (ServoConRemote.IScopeChannelPackage._s_data initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IScopeChannelPackage._s_dataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IScopeChannelPackage._s_dataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IScopeChannelPackage._s_dataHelper.type ();
  }

}
