package ServoConRemote.IScopeChannelPackage;


/**
* ServoConRemote/IScopeChannelPackage/_s_dataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

abstract public class _s_dataHelper
{
  private static String  _id = "IDL:ServoConRemote/IScopeChannel/s_data:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.IScopeChannelPackage._s_data that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.IScopeChannelPackage._s_data extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "timestamp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_any);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ServoConRemote.IScopeChannelPackage.PointsHelper.id (), "Points", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "data",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ServoConRemote.IScopeChannelPackage._s_dataHelper.id (), "s_data", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.IScopeChannelPackage._s_data read (org.omg.CORBA.portable.InputStream istream)
  {
    ServoConRemote.IScopeChannelPackage._s_data value = new ServoConRemote.IScopeChannelPackage._s_data ();
    value.timestamp = istream.read_long ();
    value.data = ServoConRemote.IScopeChannelPackage.PointsHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.IScopeChannelPackage._s_data value)
  {
    ostream.write_long (value.timestamp);
    ServoConRemote.IScopeChannelPackage.PointsHelper.write (ostream, value.data);
  }

}
