package ServoConRemote.IScopeChannelPackage;


/**
* ServoConRemote/IScopeChannelPackage/_s_data.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class _s_data implements org.omg.CORBA.portable.IDLEntity
{
  public int timestamp = (int)0;
  public org.omg.CORBA.Any data[] = null;

  public _s_data ()
  {
  } // ctor

  public _s_data (int _timestamp, org.omg.CORBA.Any[] _data)
  {
    timestamp = _timestamp;
    data = _data;
  } // ctor

} // class _s_data
