package ServoConRemote.LongProcessPackage;

/**
* ServoConRemote/LongProcessPackage/StatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//unknown means completed but status could not be retrieved
public final class StatusHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.LongProcessPackage.Status value = null;

  public StatusHolder ()
  {
  }

  public StatusHolder (ServoConRemote.LongProcessPackage.Status initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.LongProcessPackage.StatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.LongProcessPackage.StatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.LongProcessPackage.StatusHelper.type ();
  }

}
