package CosNotifyComm;


/**
* CosNotifyComm/InvalidEventType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/

public final class InvalidEventType extends org.omg.CORBA.UserException
{
  public CosNotification.EventType type = null;

  public InvalidEventType ()
  {
    super(InvalidEventTypeHelper.id());
  } // ctor

  public InvalidEventType (CosNotification.EventType _type)
  {
    super(InvalidEventTypeHelper.id());
    type = _type;
  } // ctor


  public InvalidEventType (String $reason, CosNotification.EventType _type)
  {
    super(InvalidEventTypeHelper.id() + "  " + $reason);
    type = _type;
  } // ctor

} // class InvalidEventType
