package CosNotifyComm;


/**
* CosNotifyComm/NotifySubscribeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// NotifyPublish
public interface NotifySubscribeOperations 
{
  void subscription_change (CosNotification.EventType[] added, CosNotification.EventType[] removed) throws CosNotifyComm.InvalidEventType;
} // interface NotifySubscribeOperations
