package CosNotifyComm;


/**
* CosNotifyComm/NotifySubscribe.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// NotifyPublish
public interface NotifySubscribe extends NotifySubscribeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotifySubscribe
