package CosNotifyComm;


/**
* CosNotifyComm/NotifyPublish.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/

public interface NotifyPublish extends NotifyPublishOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotifyPublish
