package CosNotifyComm;


/**
* CosNotifyComm/PullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// PushConsumer
public interface PullConsumerOperations  extends CosNotifyComm.NotifyPublishOperations, CosEventComm.PullConsumerOperations
{
} // interface PullConsumerOperations
