package CosNotifyComm;


/**
* CosNotifyComm/PullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// PullConsumer
public interface PullSupplier extends PullSupplierOperations, CosNotifyComm.NotifySubscribe, CosEventComm.PullSupplier
{
} // interface PullSupplier
