package CosNotifyComm;


/**
* CosNotifyComm/PushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// NotifySubscribe
public interface PushConsumer extends PushConsumerOperations, CosNotifyComm.NotifyPublish, CosEventComm.PushConsumer
{
} // interface PushConsumer
