package CosNotifyComm;


/**
* CosNotifyComm/PushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// PullSupplier
public interface PushSupplierOperations  extends CosNotifyComm.NotifySubscribeOperations, CosEventComm.PushSupplierOperations
{
} // interface PushSupplierOperations
