package CosNotifyComm;


/**
* CosNotifyComm/SequencePushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// SequencePullSupplier
public interface SequencePushSupplierOperations  extends CosNotifyComm.NotifySubscribeOperations
{
  void disconnect_sequence_push_supplier ();
} // interface SequencePushSupplierOperations
