package CosNotifyComm;

/**
* CosNotifyComm/SequencePullSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// SequencePullConsumer
public final class SequencePullSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyComm.SequencePullSupplier value = null;

  public SequencePullSupplierHolder ()
  {
  }

  public SequencePullSupplierHolder (CosNotifyComm.SequencePullSupplier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyComm.SequencePullSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyComm.SequencePullSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyComm.SequencePullSupplierHelper.type ();
  }

}
