package CosNotifyComm;


/**
* CosNotifyComm/SequencePushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// StructuredPushSupplier
public interface SequencePushConsumerOperations  extends CosNotifyComm.NotifyPublishOperations
{
  void push_structured_events (CosNotification.StructuredEvent[] notifications) throws CosEventComm.Disconnected;
  void disconnect_sequence_push_consumer ();
} // interface SequencePushConsumerOperations
