package CosNotifyComm;

/**
* CosNotifyComm/SequencePullConsumerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// SequencePushConsumer
public final class SequencePullConsumerHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyComm.SequencePullConsumer value = null;

  public SequencePullConsumerHolder ()
  {
  }

  public SequencePullConsumerHolder (CosNotifyComm.SequencePullConsumer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyComm.SequencePullConsumerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyComm.SequencePullConsumerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyComm.SequencePullConsumerHelper.type ();
  }

}
