package CosNotifyComm;


/**
* CosNotifyComm/SequencePullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// SequencePullConsumer
public interface SequencePullSupplier extends SequencePullSupplierOperations, CosNotifyComm.NotifySubscribe, org.omg.CORBA.portable.IDLEntity 
{
} // interface SequencePullSupplier
