package CosNotifyComm;


/**
* CosNotifyComm/SequencePullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// SequencePushConsumer
public interface SequencePullConsumerOperations  extends CosNotifyComm.NotifyPublishOperations
{
  void disconnect_sequence_pull_consumer ();
} // interface SequencePullConsumerOperations
