package CosNotifyComm;


/**
* CosNotifyComm/SequencePushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// SequencePullSupplier
public interface SequencePushSupplier extends SequencePushSupplierOperations, CosNotifyComm.NotifySubscribe, org.omg.CORBA.portable.IDLEntity 
{
} // interface SequencePushSupplier
