package CosNotifyComm;

/**
* CosNotifyComm/StructuredPushSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// StructuredPullSupplier
public final class StructuredPushSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyComm.StructuredPushSupplier value = null;

  public StructuredPushSupplierHolder ()
  {
  }

  public StructuredPushSupplierHolder (CosNotifyComm.StructuredPushSupplier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyComm.StructuredPushSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyComm.StructuredPushSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyComm.StructuredPushSupplierHelper.type ();
  }

}
