package CosNotifyComm;


/**
* CosNotifyComm/StructuredPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// StructuredPullSupplier
public interface StructuredPushSupplier extends StructuredPushSupplierOperations, CosNotifyComm.NotifySubscribe, org.omg.CORBA.portable.IDLEntity 
{
} // interface StructuredPushSupplier
