package CosNotifyComm;


/**
* CosNotifyComm/StructuredPullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// StructuredPullConsumer
public interface StructuredPullSupplier extends StructuredPullSupplierOperations, CosNotifyComm.NotifySubscribe, org.omg.CORBA.portable.IDLEntity 
{
} // interface StructuredPullSupplier
