package CosNotifyComm;


/**
* CosNotifyComm/StructuredPullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// StructuredPushConsumer
public interface StructuredPullConsumerOperations  extends CosNotifyComm.NotifyPublishOperations
{
  void disconnect_structured_pull_consumer ();
} // interface StructuredPullConsumerOperations
