package CosNotifyComm;


/**
* CosNotifyComm/StructuredPushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/

public interface StructuredPushConsumerOperations  extends CosNotifyComm.NotifyPublishOperations
{
  void push_structured_event (CosNotification.StructuredEvent notification) throws CosEventComm.Disconnected;
  void disconnect_structured_push_consumer ();
} // interface StructuredPushConsumerOperations
