package CosNotifyComm;


/**
* CosNotifyComm/StructuredPushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyComm.idl
* Wednesday, April 19, 2017 6:32:07 PM MSK
*/


// StructuredPullSupplier
public interface StructuredPushSupplierOperations  extends CosNotifyComm.NotifySubscribeOperations
{
  void disconnect_structured_push_supplier ();
} // interface StructuredPushSupplierOperations
