package ServoConRemote.IUserParameterPackage;


/**
* ServoConRemote/IUserParameterPackage/_s_LimitsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

abstract public class _s_LimitsHelper
{
  private static String  _id = "IDL:ServoConRemote/IUserParameter/s_Limits:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.IUserParameterPackage._s_Limits that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.IUserParameterPackage._s_Limits extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[0] = new org.omg.CORBA.StructMember (
            "min",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[1] = new org.omg.CORBA.StructMember (
            "max",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ServoConRemote.IUserParameterPackage._s_LimitsHelper.id (), "s_Limits", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.IUserParameterPackage._s_Limits read (org.omg.CORBA.portable.InputStream istream)
  {
    ServoConRemote.IUserParameterPackage._s_Limits value = new ServoConRemote.IUserParameterPackage._s_Limits ();
    value.min = istream.read_double ();
    value.max = istream.read_double ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.IUserParameterPackage._s_Limits value)
  {
    ostream.write_double (value.min);
    ostream.write_double (value.max);
  }

}
