package ServoConRemote.IUserParameterPackage;

/**
* ServoConRemote/IUserParameterPackage/_s_LimitsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class _s_LimitsHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IUserParameterPackage._s_Limits value = null;

  public _s_LimitsHolder ()
  {
  }

  public _s_LimitsHolder (ServoConRemote.IUserParameterPackage._s_Limits initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IUserParameterPackage._s_LimitsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IUserParameterPackage._s_LimitsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IUserParameterPackage._s_LimitsHelper.type ();
  }

}
