package ServoConRemote.IUserParameterPackage;


/**
* ServoConRemote/IUserParameterPackage/_s_Limits.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class _s_Limits implements org.omg.CORBA.portable.IDLEntity
{
  public double min = (double)0;
  public double max = (double)0;

  public _s_Limits ()
  {
  } // ctor

  public _s_Limits (double _min, double _max)
  {
    min = _min;
    max = _max;
  } // ctor

} // class _s_Limits
