package ServoConRemote.IUserParameterPackage;

/**
* ServoConRemote/IUserParameterPackage/IsReadOnlyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class IsReadOnlyHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IUserParameterPackage.IsReadOnly value = null;

  public IsReadOnlyHolder ()
  {
  }

  public IsReadOnlyHolder (ServoConRemote.IUserParameterPackage.IsReadOnly initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IUserParameterPackage.IsReadOnlyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IUserParameterPackage.IsReadOnlyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IUserParameterPackage.IsReadOnlyHelper.type ();
  }

}
