package ServoConRemote.IUserParameterPackage;


/**
* ServoConRemote/IUserParameterPackage/IsReadOnlyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

abstract public class IsReadOnlyHelper
{
  private static String  _id = "IDL:ServoConRemote/IUserParameter/IsReadOnly:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.IUserParameterPackage.IsReadOnly that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.IUserParameterPackage.IsReadOnly extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (ServoConRemote.IUserParameterPackage.IsReadOnlyHelper.id (), "IsReadOnly", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.IUserParameterPackage.IsReadOnly read (org.omg.CORBA.portable.InputStream istream)
  {
    ServoConRemote.IUserParameterPackage.IsReadOnly value = new ServoConRemote.IUserParameterPackage.IsReadOnly ();
    // read and discard the repository ID
    istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.IUserParameterPackage.IsReadOnly value)
  {
    // write the repository ID
    ostream.write_string (id ());
  }

}
