package ServoConRemote.IUserParameterPackage;


/**
* ServoConRemote/IUserParameterPackage/IsReadOnly.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class IsReadOnly extends org.omg.CORBA.UserException
{

  public IsReadOnly ()
  {
    super(IsReadOnlyHelper.id());
  } // ctor


  public IsReadOnly (String $reason)
  {
    super(IsReadOnlyHelper.id() + "  " + $reason);
  } // ctor

} // class IsReadOnly
