package ServoConRemote.IUserParameterPackage;


/**
* ServoConRemote/IUserParameterPackage/NotListType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class NotListType extends org.omg.CORBA.UserException
{

  public NotListType ()
  {
    super(NotListTypeHelper.id());
  } // ctor


  public NotListType (String $reason)
  {
    super(NotListTypeHelper.id() + "  " + $reason);
  } // ctor

} // class NotListType
