package ServoConRemote.IUserParameterPackage;

/**
* ServoConRemote/IUserParameterPackage/NotListTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class NotListTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IUserParameterPackage.NotListType value = null;

  public NotListTypeHolder ()
  {
  }

  public NotListTypeHolder (ServoConRemote.IUserParameterPackage.NotListType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IUserParameterPackage.NotListTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IUserParameterPackage.NotListTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IUserParameterPackage.NotListTypeHelper.type ();
  }

}
