package ServoConRemote.IUserParameterPackage;

/**
* ServoConRemote/IUserParameterPackage/TypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class TypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IUserParameterPackage.Type value = null;

  public TypeHolder ()
  {
  }

  public TypeHolder (ServoConRemote.IUserParameterPackage.Type initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IUserParameterPackage.TypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IUserParameterPackage.TypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IUserParameterPackage.TypeHelper.type ();
  }

}
