package ServoConRemote.IUserParameterPackage;


/**
* ServoConRemote/IUserParameterPackage/Type.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public class Type implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static ServoConRemote.IUserParameterPackage.Type[] __array = new ServoConRemote.IUserParameterPackage.Type [__size];

  public static final int _BoolType = 0;
  public static final ServoConRemote.IUserParameterPackage.Type BoolType = new ServoConRemote.IUserParameterPackage.Type(_BoolType);
  public static final int _S32Type = 1;
  public static final ServoConRemote.IUserParameterPackage.Type S32Type = new ServoConRemote.IUserParameterPackage.Type(_S32Type);
  public static final int _FloatType = 2;
  public static final ServoConRemote.IUserParameterPackage.Type FloatType = new ServoConRemote.IUserParameterPackage.Type(_FloatType);
  public static final int _StringType = 3;
  public static final ServoConRemote.IUserParameterPackage.Type StringType = new ServoConRemote.IUserParameterPackage.Type(_StringType);

  public int value ()
  {
    return __value;
  }

  public static ServoConRemote.IUserParameterPackage.Type from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Type (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Type
