package ServoConRemote.IUserParameterPackage;


/**
* ServoConRemote/IUserParameterPackage/ValueListSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//TODO: check what values
public final class ValueListSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ValueListSeqHolder ()
  {
  }

  public ValueListSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IUserParameterPackage.ValueListSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IUserParameterPackage.ValueListSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IUserParameterPackage.ValueListSeqHelper.type ();
  }

}
