package ServoConRemote.IConfigurationPackage;


/**
* ServoConRemote/IConfigurationPackage/DeviceSpecificParameterListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class DeviceSpecificParameterListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public DeviceSpecificParameterListHolder ()
  {
  }

  public DeviceSpecificParameterListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IConfigurationPackage.DeviceSpecificParameterListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IConfigurationPackage.DeviceSpecificParameterListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IConfigurationPackage.DeviceSpecificParameterListHelper.type ();
  }

}
