package ServoConRemote.IConfigurationPackage;


/**
* ServoConRemote/IConfigurationPackage/NetworkSettingsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

abstract public class NetworkSettingsHelper
{
  private static String  _id = "IDL:ServoConRemote/IConfiguration/NetworkSettings:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.IConfigurationPackage.NetworkSettings that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.IConfigurationPackage.NetworkSettings extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "manual",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "ip",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "mask",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "gate",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ServoConRemote.IConfigurationPackage.NetworkSettingsHelper.id (), "NetworkSettings", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.IConfigurationPackage.NetworkSettings read (org.omg.CORBA.portable.InputStream istream)
  {
    ServoConRemote.IConfigurationPackage.NetworkSettings value = new ServoConRemote.IConfigurationPackage.NetworkSettings ();
    value.manual = istream.read_long ();
    value.ip = istream.read_string ();
    value.mask = istream.read_string ();
    value.gate = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.IConfigurationPackage.NetworkSettings value)
  {
    ostream.write_long (value.manual);
    ostream.write_string (value.ip);
    ostream.write_string (value.mask);
    ostream.write_string (value.gate);
  }

}
