package ServoConRemote.IConfigurationPackage;


/**
* ServoConRemote/IConfigurationPackage/NetworkSettings.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class NetworkSettings implements org.omg.CORBA.portable.IDLEntity
{
  public int manual = (int)0;
  public String ip = null;
  public String mask = null;
  public String gate = null;

  public NetworkSettings ()
  {
  } // ctor

  public NetworkSettings (int _manual, String _ip, String _mask, String _gate)
  {
    manual = _manual;
    ip = _ip;
    mask = _mask;
    gate = _gate;
  } // ctor

} // class NetworkSettings
