package ServoConRemote;


/**
* ServoConRemote/_IActionStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//low-level, try to avoid
public class _IActionStub extends org.omg.CORBA.portable.ObjectImpl implements ServoConRemote.IAction
{

  public void Perform (org.omg.CORBA.Any param) throws ServoConRemote.Impossible, ServoConRemote.CNCError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("Perform", true);
                $out.write_any (param);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ServoConRemote/Impossible:1.0"))
                    throw ServoConRemote.ImpossibleHelper.read ($in);
                else if (_id.equals ("IDL:ServoConRemote/CNCError:1.0"))
                    throw ServoConRemote.CNCErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                Perform (param        );
            } finally {
                _releaseReply ($in);
            }
  } // Perform

  public ServoConRemote.LongProcess PerformLong (org.omg.CORBA.Any param) throws ServoConRemote.Impossible, ServoConRemote.CNCError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("PerformLong", true);
                $out.write_any (param);
                $in = _invoke ($out);
                ServoConRemote.LongProcess $result = ServoConRemote.LongProcessHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ServoConRemote/Impossible:1.0"))
                    throw ServoConRemote.ImpossibleHelper.read ($in);
                else if (_id.equals ("IDL:ServoConRemote/CNCError:1.0"))
                    throw ServoConRemote.CNCErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return PerformLong (param        );
            } finally {
                _releaseReply ($in);
            }
  } // PerformLong


  //do not use!!!
  public void Reset ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("Reset", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                Reset (        );
            } finally {
                _releaseReply ($in);
            }
  } // Reset


  //internal - reset internal state
  public void Flush ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("Flush", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                Flush (        );
            } finally {
                _releaseReply ($in);
            }
  } // Flush

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServoConRemote/IAction:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IActionStub
