package ServoConRemote;


/**
* ServoConRemote/_IHomingParametersStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//use with caution - see Integrator's manual
public class _IHomingParametersStub extends org.omg.CORBA.portable.ObjectImpl implements ServoConRemote.IHomingParameters
{

  public ServoConRemote.IUserParameter HomePosition ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_HomePosition", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return HomePosition (        );
            } finally {
                _releaseReply ($in);
            }
  } // HomePosition

  public ServoConRemote.IUserParameter Offset ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_Offset", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return Offset (        );
            } finally {
                _releaseReply ($in);
            }
  } // Offset

  public ServoConRemote.IUserParameter SearchVelocity ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_SearchVelocity", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return SearchVelocity (        );
            } finally {
                _releaseReply ($in);
            }
  } // SearchVelocity

  public ServoConRemote.IUserParameter LatchVelocity ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_LatchVelocity", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return LatchVelocity (        );
            } finally {
                _releaseReply ($in);
            }
  } // LatchVelocity

  public ServoConRemote.IUserParameter UseIndex ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_UseIndex", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return UseIndex (        );
            } finally {
                _releaseReply ($in);
            }
  } // UseIndex

  public ServoConRemote.IUserParameter IgnoreLimits ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_IgnoreLimits", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return IgnoreLimits (        );
            } finally {
                _releaseReply ($in);
            }
  } // IgnoreLimits

  public ServoConRemote.IUserParameter HomeSequence ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_HomeSequence", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return HomeSequence (        );
            } finally {
                _releaseReply ($in);
            }
  } // HomeSequence

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServoConRemote/IHomingParameters:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IHomingParametersStub
