package ServoConRemote;


/**
* ServoConRemote/_IJointStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//use with caution - see Integrator's manual
public class _IJointStub extends org.omg.CORBA.portable.ObjectImpl implements ServoConRemote.IJoint
{

  public ServoConRemote.IUserParameter PositionCommand ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_PositionCommand", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return PositionCommand (        );
            } finally {
                _releaseReply ($in);
            }
  } // PositionCommand

  public ServoConRemote.IUserParameter PositionFeedback ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_PositionFeedback", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return PositionFeedback (        );
            } finally {
                _releaseReply ($in);
            }
  } // PositionFeedback

  public ServoConRemote.IUserParameter MaxVelocity ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_MaxVelocity", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MaxVelocity (        );
            } finally {
                _releaseReply ($in);
            }
  } // MaxVelocity

  public ServoConRemote.IUserParameter MaxAcceleration ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_MaxAcceleration", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MaxAcceleration (        );
            } finally {
                _releaseReply ($in);
            }
  } // MaxAcceleration

  public ServoConRemote.IUserParameter MinLimit ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_MinLimit", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MinLimit (        );
            } finally {
                _releaseReply ($in);
            }
  } // MinLimit

  public ServoConRemote.IUserParameter MaxLimit ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_MaxLimit", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MaxLimit (        );
            } finally {
                _releaseReply ($in);
            }
  } // MaxLimit

  public ServoConRemote.IUserParameter FollowingError ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_FollowingError", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return FollowingError (        );
            } finally {
                _releaseReply ($in);
            }
  } // FollowingError

  public ServoConRemote.IUserParameter Backlash ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_Backlash", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return Backlash (        );
            } finally {
                _releaseReply ($in);
            }
  } // Backlash

  public ServoConRemote.IUserParameter Enabled ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_Enabled", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return Enabled (        );
            } finally {
                _releaseReply ($in);
            }
  } // Enabled

  public ServoConRemote.IUserParameter Faulted ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_Faulted", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return Faulted (        );
            } finally {
                _releaseReply ($in);
            }
  } // Faulted

  public ServoConRemote.IUserParameter MinHWLimit ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_MinHWLimit", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MinHWLimit (        );
            } finally {
                _releaseReply ($in);
            }
  } // MinHWLimit

  public ServoConRemote.IUserParameter MaxHWLimit ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_MaxHWLimit", true);
                $in = _invoke ($out);
                ServoConRemote.IUserParameter $result = ServoConRemote.IUserParameterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MaxHWLimit (        );
            } finally {
                _releaseReply ($in);
            }
  } // MaxHWLimit

  public ServoConRemote.IHomingParameters Homing ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_Homing", true);
                $in = _invoke ($out);
                ServoConRemote.IHomingParameters $result = ServoConRemote.IHomingParametersHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return Homing (        );
            } finally {
                _releaseReply ($in);
            }
  } // Homing

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServoConRemote/IJoint:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IJointStub
