package ServoConRemote;

/**
* ServoConRemote/_s_LinearMotionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class _s_LinearMotionHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote._s_LinearMotion value = null;

  public _s_LinearMotionHolder ()
  {
  }

  public _s_LinearMotionHolder (ServoConRemote._s_LinearMotion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote._s_LinearMotionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote._s_LinearMotionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote._s_LinearMotionHelper.type ();
  }

}
