package ServoConRemote;


/**
* ServoConRemote/_s_LinearMotion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class _s_LinearMotion implements org.omg.CORBA.portable.IDLEntity
{
  public ServoConRemote.Position End = null;

  public _s_LinearMotion ()
  {
  } // ctor

  public _s_LinearMotion (ServoConRemote.Position _End)
  {
    End = _End;
  } // ctor

} // class _s_LinearMotion
