package ServoConRemote;


/**
* ServoConRemote/_s_MotionInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class _s_MotionInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int Id = (int)0;

  public _s_MotionInfo ()
  {
  } // ctor

  public _s_MotionInfo (int _Id)
  {
    Id = _Id;
  } // ctor

} // class _s_MotionInfo
