package ServoConRemote;

/**
* ServoConRemote/CNCErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class CNCErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.CNCError value = null;

  public CNCErrorHolder ()
  {
  }

  public CNCErrorHolder (ServoConRemote.CNCError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.CNCErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.CNCErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.CNCErrorHelper.type ();
  }

}
