package ServoConRemote;

/**
* ServoConRemote/CNCMessageSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//internal - do not use
public final class CNCMessageSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.CNCMessageSupplier value = null;

  public CNCMessageSupplierHolder ()
  {
  }

  public CNCMessageSupplierHolder (ServoConRemote.CNCMessageSupplier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.CNCMessageSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.CNCMessageSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.CNCMessageSupplierHelper.type ();
  }

}
