package ServoConRemote;


/**
* ServoConRemote/CNCMessageConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//not needed - remove
public interface CNCMessageConsumer extends CNCMessageConsumerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CNCMessageConsumer
