package ServoConRemote;


/**
* ServoConRemote/HMICMessageConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//not needed - remove
public interface HMICMessageConsumerOperations 
{
  void push_structured_event (CosNotification.StructuredEvent notification);
  void disconnect_push_consumer ();
} // interface HMICMessageConsumerOperations
