package ServoConRemote;


/**
* ServoConRemote/IActionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//low-level, try to avoid
public interface IActionOperations 
{
  void Perform (org.omg.CORBA.Any param) throws ServoConRemote.Impossible, ServoConRemote.CNCError;
  ServoConRemote.LongProcess PerformLong (org.omg.CORBA.Any param) throws ServoConRemote.Impossible, ServoConRemote.CNCError;

  //do not use!!!
  void Reset ();

  //internal - reset internal state
  void Flush ();
} // interface IActionOperations
