package ServoConRemote;

/**
* ServoConRemote/IActionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//low-level, try to avoid
public final class IActionHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IAction value = null;

  public IActionHolder ()
  {
  }

  public IActionHolder (ServoConRemote.IAction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IActionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IActionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IActionHelper.type ();
  }

}
