package ServoConRemote;


/**
* ServoConRemote/ICNCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface ICNCOperations  extends ServoConRemote.CNCMessageSupplierOperations
{

  //to reload cnc - all references will become invalid!
  void Restart ();
  int[] GetActiveGCodes ();
  int[] GetActiveMCodes ();
  void TurnOn () throws ServoConRemote.CNCError;
  void TurnOff () throws ServoConRemote.CNCError;
  void ToggleState () throws ServoConRemote.CNCError;
  ServoConRemote.LongProcess StartHoming () throws ServoConRemote.CNCError;

  //FIXME: ExecuteCommand process may sometimes be signalled done before command is actually completed
  ServoConRemote.LongProcess ExecuteCommand (String command) throws ServoConRemote.CNCError;
  ServoConRemote.IUserParameter State ();
  ServoConRemote.Position GetPartPosition ();
  ServoConRemote.Position GetMachinePosition ();
  ServoConRemote.Position GetPositionError ();

  //stub - doesn't work yet
  ServoConRemote.IJoint Joint (int num) throws ServoConRemote.InvalidAxis;

  //handles execution of programs (AUTO mode)
  ServoConRemote.IMotionProgram MotionProgram ();

  //handles import/export
  ServoConRemote.IConfiguration Configuration ();
  ServoConRemote.IHMIC HMIC ();
  ServoConRemote.IScope Scope ();
  ServoConRemote.ITools Tools ();
  ServoConRemote.IOffsets Offsets ();
  ServoConRemote.ILocale Locale ();
  ServoConRemote.IStorage Storage ();

  //low-level
  ServoConRemote.IUserParameter Parameter (String name) throws ServoConRemote.NotFound;
  ServoConRemote.IUserParameter CreateParameter (String name, ServoConRemote.IUserParameterPackage.Type type);
  ServoConRemote.IUserParameter CreatePersistent (String name, ServoConRemote.IUserParameterPackage.Type type);

  //low-level - avoid if possible!!!
  ServoConRemote.IAction Action (String name) throws ServoConRemote.NotFound;
  void StartSelfTest ();
} // interface ICNCOperations
