package ServoConRemote;


/**
* ServoConRemote/ICNC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface ICNC extends ICNCOperations, ServoConRemote.CNCMessageSupplier, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICNC
