package ServoConRemote;


/**
* ServoConRemote/IConfigurationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface IConfigurationOperations 
{
  void SetupNetwork (ServoConRemote.IConfigurationPackage.NetworkSettings params);
  ServoConRemote.IConfigurationPackage.NetworkSettings GetNetworkSetup ();
  void UpdateFirmware ();
  void Upload (byte[] data);
  byte[] Download ();

  //for initial CNC setup ONLY
  void UploadDeviceSpecific (byte[] data);
  String[] DeviceSpecificParameters ();
  void SetDeviceSpecificParameter (String param, String value, int applyAtOnce) throws ServoConRemote.NotFound, ServoConRemote.Impossible;

  //SYSTEM ONLY
  void SetDeviceSpecific (String param, String value, int applyAtOnce);
  String GetDeviceSpecificParameter (String param) throws ServoConRemote.NotFound;
  void Apply ();

  //get config names from usb disk
  String[] GetConfigs () throws ServoConRemote.NotFound;

  //config is imported with Action('ImportConfig').Perform(path)
  void ExportAs (String path);
  void ImportAs (String path);
} // interface IConfigurationOperations
