package ServoConRemote;

/**
* ServoConRemote/IDiagnosticsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class IDiagnosticsHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IDiagnostics value = null;

  public IDiagnosticsHolder ()
  {
  }

  public IDiagnosticsHolder (ServoConRemote.IDiagnostics initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IDiagnosticsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IDiagnosticsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IDiagnosticsHelper.type ();
  }

}
