package ServoConRemote;


/**
* ServoConRemote/IDiagScreenHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//plcs should use these interfaces to let user adjust parameters
abstract public class IDiagScreenHelper
{
  private static String  _id = "IDL:ServoConRemote/IDiagScreen:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.IDiagScreen that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.IDiagScreen extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServoConRemote.IDiagScreenHelper.id (), "IDiagScreen");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.IDiagScreen read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IDiagScreenStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.IDiagScreen value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServoConRemote.IDiagScreen narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServoConRemote.IDiagScreen)
      return (ServoConRemote.IDiagScreen)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServoConRemote._IDiagScreenStub stub = new ServoConRemote._IDiagScreenStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServoConRemote.IDiagScreen unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServoConRemote.IDiagScreen)
      return (ServoConRemote.IDiagScreen)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServoConRemote._IDiagScreenStub stub = new ServoConRemote._IDiagScreenStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
