package ServoConRemote;


/**
* ServoConRemote/IDiagScreenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//plcs should use these interfaces to let user adjust parameters
public interface IDiagScreenOperations 
{

  //as they may be changed by user
  void AddParameter (String display, int len, ServoConRemote.IUserParameter param);
} // interface IDiagScreenOperations
