package ServoConRemote;


/**
* ServoConRemote/IDiagScreen.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//plcs should use these interfaces to let user adjust parameters
public interface IDiagScreen extends IDiagScreenOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IDiagScreen
