package ServoConRemote;


/**
* ServoConRemote/IDriveOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface IDriveOperations 
{
  String Name ();
  void Mount ();
  void Unmount ();
  String[] GetFileList ();
  String[] GetFileListEx (String ext);

  //copy to user-defined path on device
  void CopyFile (ServoConRemote.IDrive from, String name) throws ServoConRemote.NotFound;
  void DeleteFile (String name) throws ServoConRemote.NotFound;

  //get full content
  String GetFileContent (String name) throws ServoConRemote.NotFound;

  //get line
  String GetFileLine (String name, int line) throws ServoConRemote.NotFound;
} // interface IDriveOperations
