package ServoConRemote;

/**
* ServoConRemote/IDriveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class IDriveHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IDrive value = null;

  public IDriveHolder ()
  {
  }

  public IDriveHolder (ServoConRemote.IDrive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IDriveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IDriveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IDriveHelper.type ();
  }

}
