package ServoConRemote;

/**
* ServoConRemote/IHMICHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//front panel HW interface
public final class IHMICHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IHMIC value = null;

  public IHMICHolder ()
  {
  }

  public IHMICHolder (ServoConRemote.IHMIC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IHMICHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IHMICHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IHMICHelper.type ();
  }

}
