package ServoConRemote;


/**
* ServoConRemote/IHMICOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//front panel HW interface
public interface IHMICOperations 
{
  void Print (String data);
  void Clear ();
  void SetLed (int led, int state);
  void SetAutorepeat (ServoConRemote.IHMICPackage.AutorepeatSettings sett);
  ServoConRemote.IHMICPackage.AutorepeatSettings GetAutorepeat ();
  ServoConRemote.LongProcess Update () throws ServoConRemote.Impossible;
  ServoConRemote.IHMICPackage.DeviceDescriptor GetDeviceDescriptor ();
  void SetDeviceDescriptor (ServoConRemote.IHMICPackage.DeviceDescriptor data);
  String GetVersion ();
} // interface IHMICOperations
