package ServoConRemote;

/**
* ServoConRemote/IHomingParametersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//use with caution - see Integrator's manual
public final class IHomingParametersHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IHomingParameters value = null;

  public IHomingParametersHolder ()
  {
  }

  public IHomingParametersHolder (ServoConRemote.IHomingParameters initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IHomingParametersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IHomingParametersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IHomingParametersHelper.type ();
  }

}
