package ServoConRemote;


/**
* ServoConRemote/IHomingParametersOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//use with caution - see Integrator's manual
public interface IHomingParametersOperations 
{
  ServoConRemote.IUserParameter HomePosition ();
  ServoConRemote.IUserParameter Offset ();
  ServoConRemote.IUserParameter SearchVelocity ();
  ServoConRemote.IUserParameter LatchVelocity ();
  ServoConRemote.IUserParameter UseIndex ();
  ServoConRemote.IUserParameter IgnoreLimits ();
  ServoConRemote.IUserParameter HomeSequence ();
} // interface IHomingParametersOperations
