package ServoConRemote;


/**
* ServoConRemote/IJointOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//use with caution - see Integrator's manual
public interface IJointOperations 
{
  ServoConRemote.IUserParameter PositionCommand ();
  ServoConRemote.IUserParameter PositionFeedback ();
  ServoConRemote.IUserParameter MaxVelocity ();
  ServoConRemote.IUserParameter MaxAcceleration ();
  ServoConRemote.IUserParameter MinLimit ();
  ServoConRemote.IUserParameter MaxLimit ();
  ServoConRemote.IUserParameter FollowingError ();
  ServoConRemote.IUserParameter Backlash ();
  ServoConRemote.IUserParameter Enabled ();
  ServoConRemote.IUserParameter Faulted ();
  ServoConRemote.IUserParameter MinHWLimit ();
  ServoConRemote.IUserParameter MaxHWLimit ();
  ServoConRemote.IHomingParameters Homing ();
} // interface IJointOperations
