package ServoConRemote;

/**
* ServoConRemote/IJointHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//use with caution - see Integrator's manual
public final class IJointHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IJoint value = null;

  public IJointHolder ()
  {
  }

  public IJointHolder (ServoConRemote.IJoint initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IJointHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IJointHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IJointHelper.type ();
  }

}
