package ServoConRemote;


/**
* ServoConRemote/ILocaleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface ILocaleOperations 
{
  String[] GetAvailable ();
  String GetCurrent ();
  String GetInternalName (String locale) throws ServoConRemote.NotFound;
  void Set (String locale) throws ServoConRemote.NotFound;
} // interface ILocaleOperations
