package ServoConRemote;


/**
* ServoConRemote/IMotionProgramOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//operations on motion program
public interface IMotionProgramOperations 
{

  //mb scales (spindle too) should be in ICNC
  ServoConRemote.IUserParameter FeedScale ();
  ServoConRemote.IUserParameter TraverseScale ();

  //get list of all available programs
  String[] GetPrograms ();

  //mounts remote dir (smb share)
  void MountShared (String path, String user, String password);
  void UnMountShared ();

  //NOTE: may have \r\n inside
  String GetProgramText (String name) throws ServoConRemote.NotFound;

  //NOTE: already open program can be deleted but will still run until another program is opened
  void DeleteProgram (String name) throws ServoConRemote.NotFound;

  //create program on CNC disk, overwriting existing
  void Upload (String name, String data);

  //prepare to load program from selected file, not needed for manual load control
  void Open (String path) throws ServoConRemote.NotFound, ServoConRemote.SyntaxError, ServoConRemote.Impossible;

  //WARNING: can have unpredicted consequences if line is not the same where motion
  ServoConRemote.LongProcess StartLoad (int line, int shouldResume, int isDryRun) throws ServoConRemote.CNCError, ServoConRemote.Impossible;

  //stops execution allowing restart
  void StopLoad ();
  ServoConRemote.LongProcess GoToLineStart (int lineTo, int backwards) throws ServoConRemote.CNCError, ServoConRemote.Impossible;
  void StartTrace (int line);
  void StopTrace ();
  void TraceForward ();
  void TraceBackward ();
  int CanResume ();

  //number of lines in current program
  int Length ();

  //index of currently executing line (test how comments are handled!)
  int GetCurrentLineIndex ();

  //use only after StopLoad() and LongProcess returned from StartLoad() returns Done
  int GetPausedLineIndex ();

  //one string from loaded program (mb not needed)
  String GetLine (int index);

  //Manuaal Loader
  void Reset ();

  //typedef struct _s_Line{string line; long last;} LineData;
  int FeedLine (String line);

  //start execution
  void Start () throws ServoConRemote.CNCError;
  void Stop ();
  void Pause ();
  void Step () throws ServoConRemote.CNCError;
} // interface IMotionProgramOperations
