package ServoConRemote;


/**
* ServoConRemote/IMotionProgram.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//operations on motion program
public interface IMotionProgram extends IMotionProgramOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IMotionProgram
