package ServoConRemote;


/**
* ServoConRemote/Impossible.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class Impossible extends org.omg.CORBA.UserException
{
  public String why = null;

  public Impossible ()
  {
    super(ImpossibleHelper.id());
  } // ctor

  public Impossible (String _why)
  {
    super(ImpossibleHelper.id());
    why = _why;
  } // ctor


  public Impossible (String $reason, String _why)
  {
    super(ImpossibleHelper.id() + "  " + $reason);
    why = _why;
  } // ctor

} // class Impossible
