package ServoConRemote;


/**
* ServoConRemote/InvalidAxis.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class InvalidAxis extends org.omg.CORBA.UserException
{

  public InvalidAxis ()
  {
    super(InvalidAxisHelper.id());
  } // ctor


  public InvalidAxis (String $reason)
  {
    super(InvalidAxisHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidAxis
