package ServoConRemote;

/**
* ServoConRemote/IOffsetsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class IOffsetsHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IOffsets value = null;

  public IOffsetsHolder ()
  {
  }

  public IOffsetsHolder (ServoConRemote.IOffsets initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IOffsetsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IOffsetsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IOffsetsHelper.type ();
  }

}
