package ServoConRemote;


/**
* ServoConRemote/IScopeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface IScopeOperations 
{
  ServoConRemote.IScopeChannel AddChannel (String name) throws ServoConRemote.NotFound, ServoConRemote.IScopePackage.TooManyChannels, ServoConRemote.IScopePackage.NotGatherable;
  void RemoveChannel (ServoConRemote.IScopeChannel channel);
  void Start ();
  void Stop ();
} // interface IScopeOperations
