package ServoConRemote;

/**
* ServoConRemote/IScopeChannelHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//realtime watch - no more than 4 params at once
public final class IScopeChannelHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IScopeChannel value = null;

  public IScopeChannelHolder ()
  {
  }

  public IScopeChannelHolder (ServoConRemote.IScopeChannel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IScopeChannelHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IScopeChannelHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IScopeChannelHelper.type ();
  }

}
