package ServoConRemote;


/**
* ServoConRemote/IScopeChannel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//realtime watch - no more than 4 params at once
public interface IScopeChannel extends IScopeChannelOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IScopeChannel
