package ServoConRemote;

/**
* ServoConRemote/IScopeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class IScopeHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IScope value = null;

  public IScopeHolder ()
  {
  }

  public IScopeHolder (ServoConRemote.IScope initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IScopeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IScopeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IScopeHelper.type ();
  }

}
