package ServoConRemote;


/**
* ServoConRemote/ISpindleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface ISpindleOperations 
{

  //not implemented yet
  void TurnOn () throws ServoConRemote.CNCError;
  void TurnOff () throws ServoConRemote.CNCError;
  ServoConRemote.IUserParameter SpeedCommand ();
  ServoConRemote.IUserParameter SpeedFeedback ();
  ServoConRemote.IUserParameter Scale ();
} // interface ISpindleOperations
