package ServoConRemote;


/**
* ServoConRemote/IStorageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface IStorageOperations 
{
  ServoConRemote.IDrive[] GetDrives ();
  String[] GetSupportedTypes ();
} // interface IStorageOperations
