package ServoConRemote;

/**
* ServoConRemote/IStorageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class IStorageHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IStorage value = null;

  public IStorageHolder ()
  {
  }

  public IStorageHolder (ServoConRemote.IStorage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IStorageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IStorageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IStorageHelper.type ();
  }

}
