package ServoConRemote;

/**
* ServoConRemote/IToolsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class IToolsHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.ITools value = null;

  public IToolsHolder ()
  {
  }

  public IToolsHolder (ServoConRemote.ITools initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IToolsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IToolsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IToolsHelper.type ();
  }

}
