package ServoConRemote;


/**
* ServoConRemote/IToolsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public interface IToolsOperations 
{
  ServoConRemote.IToolsPackage._s_tool[] GetTools ();
  void SetTool (int index, ServoConRemote.IToolsPackage._s_tool data);
} // interface IToolsOperations
