package ServoConRemote;


/**
* ServoConRemote/IUserParameterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public interface IUserParameterOperations 
{

  //text name
  String Name ();
  String Hint ();
  ServoConRemote.IUserParameterPackage._s_Limits Limits ();

  //returns up to 8 digits after point
  String GetTextValue ();
  org.omg.CORBA.Any GetValue ();

  //get all possible values
  String[] GetValuesList () throws ServoConRemote.IUserParameterPackage.NotListType;

  //should recognize text and correct value type for parameter
  void SetValue (org.omg.CORBA.Any val) throws ServoConRemote.IUserParameterPackage.IsReadOnly, ServoConRemote.IUserParameterPackage.InvalidValue, ServoConRemote.Impossible;

  //not implemented yet
  void StartWatch ();

  //stop updating notification channel, mb destroy the channel
  void StopWatch ();
} // interface IUserParameterOperations
