package ServoConRemote;

/**
* ServoConRemote/IUserParameterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class IUserParameterHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IUserParameter value = null;

  public IUserParameterHolder ()
  {
  }

  public IUserParameterHolder (ServoConRemote.IUserParameter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IUserParameterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IUserParameterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IUserParameterHelper.type ();
  }

}
