package ServoConRemote;


/**
* ServoConRemote/LinearMotionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

abstract public class LinearMotionHelper
{
  private static String  _id = "IDL:ServoConRemote/LinearMotion:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote._s_LinearMotion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote._s_LinearMotion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ServoConRemote._s_LinearMotionHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ServoConRemote.LinearMotionHelper.id (), "LinearMotion", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote._s_LinearMotion read (org.omg.CORBA.portable.InputStream istream)
  {
    ServoConRemote._s_LinearMotion value = null;
    value = ServoConRemote._s_LinearMotionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote._s_LinearMotion value)
  {
    ServoConRemote._s_LinearMotionHelper.write (ostream, value);
  }

}
