package ServoConRemote;

/**
* ServoConRemote/LongProcessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//waiting for long process - pull model
public final class LongProcessHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.LongProcess value = null;

  public LongProcessHolder ()
  {
  }

  public LongProcessHolder (ServoConRemote.LongProcess initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.LongProcessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.LongProcessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.LongProcessHelper.type ();
  }

}
