package ServoConRemote;


/**
* ServoConRemote/LongProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//waiting for long process - pull model
public interface LongProcessOperations 
{
  ServoConRemote.LongProcessPackage.Status Completed ();

  //message is empty on success
  String Message ();
  double Progress ();
  void Detach ();
} // interface LongProcessOperations
