package ServoConRemote;

/**
* ServoConRemote/MotionPlaneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class MotionPlaneHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.MotionPlane value = null;

  public MotionPlaneHolder ()
  {
  }

  public MotionPlaneHolder (ServoConRemote.MotionPlane initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.MotionPlaneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.MotionPlaneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.MotionPlaneHelper.type ();
  }

}
