package ServoConRemote;


/**
* ServoConRemote/MotionTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

abstract public class MotionTypeHelper
{
  private static String  _id = "IDL:ServoConRemote/MotionType:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.MotionType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.MotionType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (ServoConRemote.MotionTypeHelper.id (), "MotionType", new String[] { "LinearMotionType", "ArcMotionType", "ProgramStartType"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.MotionType read (org.omg.CORBA.portable.InputStream istream)
  {
    return ServoConRemote.MotionType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.MotionType value)
  {
    ostream.write_long (value.value ());
  }

}
