package ServoConRemote;

/**
* ServoConRemote/MotionTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class MotionTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.MotionType value = null;

  public MotionTypeHolder ()
  {
  }

  public MotionTypeHolder (ServoConRemote.MotionType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.MotionTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.MotionTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.MotionTypeHelper.type ();
  }

}
