package ServoConRemote;


/**
* ServoConRemote/MotionType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public class MotionType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static ServoConRemote.MotionType[] __array = new ServoConRemote.MotionType [__size];

  public static final int _LinearMotionType = 0;
  public static final ServoConRemote.MotionType LinearMotionType = new ServoConRemote.MotionType(_LinearMotionType);
  public static final int _ArcMotionType = 1;
  public static final ServoConRemote.MotionType ArcMotionType = new ServoConRemote.MotionType(_ArcMotionType);
  public static final int _ProgramStartType = 2;
  public static final ServoConRemote.MotionType ProgramStartType = new ServoConRemote.MotionType(_ProgramStartType);

  public int value ()
  {
    return __value;
  }

  public static ServoConRemote.MotionType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected MotionType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class MotionType
