package ServoConRemote;


/**
* ServoConRemote/MotionPlane.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public class MotionPlane implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static ServoConRemote.MotionPlane[] __array = new ServoConRemote.MotionPlane [__size];

  public static final int _XY = 0;
  public static final ServoConRemote.MotionPlane XY = new ServoConRemote.MotionPlane(_XY);
  public static final int _XZ = 1;
  public static final ServoConRemote.MotionPlane XZ = new ServoConRemote.MotionPlane(_XZ);
  public static final int _YZ = 2;
  public static final ServoConRemote.MotionPlane YZ = new ServoConRemote.MotionPlane(_YZ);

  public int value ()
  {
    return __value;
  }

  public static ServoConRemote.MotionPlane from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected MotionPlane (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class MotionPlane
