package ServoConRemote;

/**
* ServoConRemote/NotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class NotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.NotFound value = null;

  public NotFoundHolder ()
  {
  }

  public NotFoundHolder (ServoConRemote.NotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.NotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.NotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.NotFoundHelper.type ();
  }

}
