package ServoConRemote;

/**
* ServoConRemote/NotHomedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//not used yet
public final class NotHomedHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.NotHomed value = null;

  public NotHomedHolder ()
  {
  }

  public NotHomedHolder (ServoConRemote.NotHomed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.NotHomedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.NotHomedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.NotHomedHelper.type ();
  }

}
