package ServoConRemote;


/**
* ServoConRemote/NotHomed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/


//not used yet
public final class NotHomed extends org.omg.CORBA.UserException
{

  public NotHomed ()
  {
    super(NotHomedHelper.id());
  } // ctor


  public NotHomed (String $reason)
  {
    super(NotHomedHelper.id() + "  " + $reason);
  } // ctor

} // class NotHomed
