package ServoConRemote;


/**
* ServoConRemote/Position.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class Position implements org.omg.CORBA.portable.IDLEntity
{
  public double X = (double)0;
  public double Y = (double)0;
  public double Z = (double)0;
  public double A = (double)0;
  public double B = (double)0;
  public double C = (double)0;
  public double U = (double)0;
  public double V = (double)0;
  public double W = (double)0;

  public Position ()
  {
  } // ctor

  public Position (double _X, double _Y, double _Z, double _A, double _B, double _C, double _U, double _V, double _W)
  {
    X = _X;
    Y = _Y;
    Z = _Z;
    A = _A;
    B = _B;
    C = _C;
    U = _U;
    V = _V;
    W = _W;
  } // ctor

} // class Position
