package ServoConRemote;


/**
* ServoConRemote/SyntaxError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:20 PM MSK
*/

public final class SyntaxError extends org.omg.CORBA.UserException
{
  public String Text = null;
  public int Line = (int)0;

  public SyntaxError ()
  {
    super(SyntaxErrorHelper.id());
  } // ctor

  public SyntaxError (String _Text, int _Line)
  {
    super(SyntaxErrorHelper.id());
    Text = _Text;
    Line = _Line;
  } // ctor


  public SyntaxError (String $reason, String _Text, int _Line)
  {
    super(SyntaxErrorHelper.id() + "  " + $reason);
    Text = _Text;
    Line = _Line;
  } // ctor

} // class SyntaxError
