package ServoConRemote.IToolsPackage;


/**
* ServoConRemote/IToolsPackage/_s_tool.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class _s_tool implements org.omg.CORBA.portable.IDLEntity
{
  public int number = (int)0;
  public int pocket = (int)0;
  public double lengthX = (double)0;
  public double lengthZ = (double)0;
  public double diameter = (double)0;

  public _s_tool ()
  {
  } // ctor

  public _s_tool (int _number, int _pocket, double _lengthX, double _lengthZ, double _diameter)
  {
    number = _number;
    pocket = _pocket;
    lengthX = _lengthX;
    lengthZ = _lengthZ;
    diameter = _diameter;
  } // ctor

} // class _s_tool
