package ServoConRemote.IToolsPackage;


/**
* ServoConRemote/IToolsPackage/ToolHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

abstract public class ToolHelper
{
  private static String  _id = "IDL:ServoConRemote/ITools/Tool:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.IToolsPackage._s_tool that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.IToolsPackage._s_tool extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ServoConRemote.IToolsPackage._s_toolHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ServoConRemote.IToolsPackage.ToolHelper.id (), "Tool", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.IToolsPackage._s_tool read (org.omg.CORBA.portable.InputStream istream)
  {
    ServoConRemote.IToolsPackage._s_tool value = null;
    value = ServoConRemote.IToolsPackage._s_toolHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.IToolsPackage._s_tool value)
  {
    ServoConRemote.IToolsPackage._s_toolHelper.write (ostream, value);
  }

}
