package ServoConRemote.IHMICPackage;


/**
* ServoConRemote/IHMICPackage/_a_ExtraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class _a_ExtraHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public _a_ExtraHolder ()
  {
  }

  public _a_ExtraHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IHMICPackage._a_ExtraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IHMICPackage._a_ExtraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IHMICPackage._a_ExtraHelper.type ();
  }

}
