package ServoConRemote.IHMICPackage;

/**
* ServoConRemote/IHMICPackage/AutorepeatSettingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class AutorepeatSettingsHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IHMICPackage.AutorepeatSettings value = null;

  public AutorepeatSettingsHolder ()
  {
  }

  public AutorepeatSettingsHolder (ServoConRemote.IHMICPackage.AutorepeatSettings initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IHMICPackage.AutorepeatSettingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IHMICPackage.AutorepeatSettingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IHMICPackage.AutorepeatSettingsHelper.type ();
  }

}
