package ServoConRemote.IHMICPackage;


/**
* ServoConRemote/IHMICPackage/AutorepeatSettings.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class AutorepeatSettings implements org.omg.CORBA.portable.IDLEntity
{
  public int startDelay = (int)0;
  public int repeatDelay = (int)0;

  public AutorepeatSettings ()
  {
  } // ctor

  public AutorepeatSettings (int _startDelay, int _repeatDelay)
  {
    startDelay = _startDelay;
    repeatDelay = _repeatDelay;
  } // ctor

} // class AutorepeatSettings
