package ServoConRemote.IHMICPackage;

/**
* ServoConRemote/IHMICPackage/DeviceDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class DeviceDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IHMICPackage.DeviceDescriptor value = null;

  public DeviceDescriptorHolder ()
  {
  }

  public DeviceDescriptorHolder (ServoConRemote.IHMICPackage.DeviceDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IHMICPackage.DeviceDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IHMICPackage.DeviceDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IHMICPackage.DeviceDescriptorHelper.type ();
  }

}
