package ServoConRemote.IHMICPackage;


/**
* ServoConRemote/IHMICPackage/DeviceDescriptorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

abstract public class DeviceDescriptorHelper
{
  private static String  _id = "IDL:ServoConRemote/IHMIC/DeviceDescriptor:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.IHMICPackage.DeviceDescriptor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.IHMICPackage.DeviceDescriptor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "writeCount",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "password",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "deviceType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "deviceId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "manufDate",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "manufTime",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (80, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ServoConRemote.IHMICPackage._a_ExtraHelper.id (), "a_Extra", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "extra",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ServoConRemote.IHMICPackage.DeviceDescriptorHelper.id (), "DeviceDescriptor", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.IHMICPackage.DeviceDescriptor read (org.omg.CORBA.portable.InputStream istream)
  {
    ServoConRemote.IHMICPackage.DeviceDescriptor value = new ServoConRemote.IHMICPackage.DeviceDescriptor ();
    value.writeCount = istream.read_long ();
    value.password = istream.read_long ();
    value.deviceType = istream.read_long ();
    value.deviceId = istream.read_long ();
    value.manufDate = istream.read_long ();
    value.manufTime = istream.read_long ();
    value.extra = ServoConRemote.IHMICPackage._a_ExtraHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.IHMICPackage.DeviceDescriptor value)
  {
    ostream.write_long (value.writeCount);
    ostream.write_long (value.password);
    ostream.write_long (value.deviceType);
    ostream.write_long (value.deviceId);
    ostream.write_long (value.manufDate);
    ostream.write_long (value.manufTime);
    ServoConRemote.IHMICPackage._a_ExtraHelper.write (ostream, value.extra);
  }

}
