package ServoConRemote.IHMICPackage;


/**
* ServoConRemote/IHMICPackage/DeviceDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class DeviceDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public int writeCount = (int)0;
  public int password = (int)0;
  public int deviceType = (int)0;
  public int deviceId = (int)0;
  public int manufDate = (int)0;
  public int manufTime = (int)0;
  public byte extra[] = null;

  public DeviceDescriptor ()
  {
  } // ctor

  public DeviceDescriptor (int _writeCount, int _password, int _deviceType, int _deviceId, int _manufDate, int _manufTime, byte[] _extra)
  {
    writeCount = _writeCount;
    password = _password;
    deviceType = _deviceType;
    deviceId = _deviceId;
    manufDate = _manufDate;
    manufTime = _manufTime;
    extra = _extra;
  } // ctor

} // class DeviceDescriptor
