package CosEventComm;


/**
* CosEventComm/PullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* Wednesday, April 19, 2017 6:31:31 PM MSK
*/

public interface PullConsumer extends PullConsumerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PullConsumer
