package CosEventComm;


/**
* CosEventComm/PullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* Wednesday, April 19, 2017 6:31:31 PM MSK
*/

public interface PullSupplierOperations 
{
  org.omg.CORBA.Any pull () throws CosEventComm.Disconnected;
  org.omg.CORBA.Any try_pull (org.omg.CORBA.BooleanHolder has_event) throws CosEventComm.Disconnected;
  void disconnect_pull_supplier ();
} // interface PullSupplierOperations
