package CosEventComm;


/**
* CosEventComm/PushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* Wednesday, April 19, 2017 6:31:31 PM MSK
*/

public interface PushConsumerOperations 
{
  void push (org.omg.CORBA.Any data) throws CosEventComm.Disconnected;
  void disconnect_push_consumer ();
} // interface PushConsumerOperations
