package CosEventComm;


/**
* CosEventComm/PushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* Wednesday, April 19, 2017 6:31:31 PM MSK
*/

public interface PushSupplierOperations 
{
  void disconnect_push_supplier ();
} // interface PushSupplierOperations
