package ServoConRemote.IStoragePackage;


/**
* ServoConRemote/IStoragePackage/DriveSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class DriveSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IDrive value[] = null;

  public DriveSeqHolder ()
  {
  }

  public DriveSeqHolder (ServoConRemote.IDrive[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IStoragePackage.DriveSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IStoragePackage.DriveSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IStoragePackage.DriveSeqHelper.type ();
  }

}
