package ServoConRemote.IStoragePackage;


/**
* ServoConRemote/IStoragePackage/FormatSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class FormatSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public FormatSeqHolder ()
  {
  }

  public FormatSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IStoragePackage.FormatSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IStoragePackage.FormatSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IStoragePackage.FormatSeqHelper.type ();
  }

}
