package ServoConRemote.IScopePackage;

/**
* ServoConRemote/IScopePackage/NotGatherableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class NotGatherableHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IScopePackage.NotGatherable value = null;

  public NotGatherableHolder ()
  {
  }

  public NotGatherableHolder (ServoConRemote.IScopePackage.NotGatherable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IScopePackage.NotGatherableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IScopePackage.NotGatherableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IScopePackage.NotGatherableHelper.type ();
  }

}
