package ServoConRemote.IScopePackage;

/**
* ServoConRemote/IScopePackage/TooManyChannelsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class TooManyChannelsHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.IScopePackage.TooManyChannels value = null;

  public TooManyChannelsHolder ()
  {
  }

  public TooManyChannelsHolder (ServoConRemote.IScopePackage.TooManyChannels initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IScopePackage.TooManyChannelsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IScopePackage.TooManyChannelsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IScopePackage.TooManyChannelsHelper.type ();
  }

}
