package ServoConRemote.ILocalePackage;


/**
* ServoConRemote/ILocalePackage/LocaleListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class LocaleListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public LocaleListHolder ()
  {
  }

  public LocaleListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.ILocalePackage.LocaleListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.ILocalePackage.LocaleListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.ILocalePackage.LocaleListHelper.type ();
  }

}
