package ServoConRemote.IDrivePackage;


/**
* ServoConRemote/IDrivePackage/FileSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class FileSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public FileSeqHolder ()
  {
  }

  public FileSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.IDrivePackage.FileSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.IDrivePackage.FileSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.IDrivePackage.FileSeqHelper.type ();
  }

}
