package ServoConRemote.ICNCPackage;


/**
* ServoConRemote/ICNCPackage/CNCState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public class CNCState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static ServoConRemote.ICNCPackage.CNCState[] __array = new ServoConRemote.ICNCPackage.CNCState [__size];

  public static final int _On = 0;
  public static final ServoConRemote.ICNCPackage.CNCState On = new ServoConRemote.ICNCPackage.CNCState(_On);
  public static final int _EStop = 1;
  public static final ServoConRemote.ICNCPackage.CNCState EStop = new ServoConRemote.ICNCPackage.CNCState(_EStop);
  public static final int _Reset = 2;
  public static final ServoConRemote.ICNCPackage.CNCState Reset = new ServoConRemote.ICNCPackage.CNCState(_Reset);

  public int value ()
  {
    return __value;
  }

  public static ServoConRemote.ICNCPackage.CNCState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CNCState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CNCState
