package ServoConRemote.ICNCPackage;


/**
* ServoConRemote/ICNCPackage/CNCStateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

abstract public class CNCStateHelper
{
  private static String  _id = "IDL:ServoConRemote/ICNC/CNCState:1.0";

  public static void insert (org.omg.CORBA.Any a, ServoConRemote.ICNCPackage.CNCState that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServoConRemote.ICNCPackage.CNCState extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (ServoConRemote.ICNCPackage.CNCStateHelper.id (), "CNCState", new String[] { "On", "EStop", "Reset"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServoConRemote.ICNCPackage.CNCState read (org.omg.CORBA.portable.InputStream istream)
  {
    return ServoConRemote.ICNCPackage.CNCState.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServoConRemote.ICNCPackage.CNCState value)
  {
    ostream.write_long (value.value ());
  }

}
