package ServoConRemote.ICNCPackage;

/**
* ServoConRemote/ICNCPackage/CNCStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/

public final class CNCStateHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.ICNCPackage.CNCState value = null;

  public CNCStateHolder ()
  {
  }

  public CNCStateHolder (ServoConRemote.ICNCPackage.CNCState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.ICNCPackage.CNCStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.ICNCPackage.CNCStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.ICNCPackage.CNCStateHelper.type ();
  }

}
