package ServoConRemote.ICNCPackage;


/**
* ServoConRemote/ICNCPackage/InvalidState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//not used yet
public final class InvalidState extends org.omg.CORBA.UserException
{

  public InvalidState ()
  {
    super(InvalidStateHelper.id());
  } // ctor


  public InvalidState (String $reason)
  {
    super(InvalidStateHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidState
