package ServoConRemote.ICNCPackage;

/**
* ServoConRemote/ICNCPackage/InvalidStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//not used yet
public final class InvalidStateHolder implements org.omg.CORBA.portable.Streamable
{
  public ServoConRemote.ICNCPackage.InvalidState value = null;

  public InvalidStateHolder ()
  {
  }

  public InvalidStateHolder (ServoConRemote.ICNCPackage.InvalidState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServoConRemote.ICNCPackage.InvalidStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServoConRemote.ICNCPackage.InvalidStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServoConRemote.ICNCPackage.InvalidStateHelper.type ();
  }

}
