package ServoConRemote.ICNCPackage;


/**
* ServoConRemote/ICNCPackage/InvalidMode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServoConRemote_v2.idl
* Wednesday, April 19, 2017 6:32:21 PM MSK
*/


//not used yet - will be removed (use Impossible!)
public final class InvalidMode extends org.omg.CORBA.UserException
{

  public InvalidMode ()
  {
    super(InvalidModeHelper.id());
  } // ctor


  public InvalidMode (String $reason)
  {
    super(InvalidModeHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidMode
