package CosNotification;


/**
* CosNotification/AdminPropertiesAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/


// RejectNewEvents takes on a value of type Boolean
public interface AdminPropertiesAdminOperations 
{
  CosNotification.Property[] get_admin ();
  void set_admin (CosNotification.Property[] admin) throws CosNotification.UnsupportedAdmin;
} // interface AdminPropertiesAdminOperations
