package CosNotification;


/**
* CosNotification/LifoOrder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/

public interface LifoOrder
{

  // DiscardPolicy takes on the same values as OrderPolicy, plus
  public static final short value = (short)(4);
}
