package CosNotification;


/**
* CosNotification/MaximumBatchSize.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/

public interface MaximumBatchSize
{
  public static final String value = "MaximumBatchSize";
}
