package CosNotification;


/**
* CosNotification/MaxQueueLength.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/

public interface MaxQueueLength
{

  // message quality of service
  public static final String value = "MaxQueueLength";
}
