package CosNotification;


/**
* CosNotification/NamedPropertyRange.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/

public final class NamedPropertyRange implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public CosNotification.PropertyRange range = null;

  public NamedPropertyRange ()
  {
  } // ctor

  public NamedPropertyRange (String _name, CosNotification.PropertyRange _range)
  {
    name = _name;
    range = _range;
  } // ctor

} // class NamedPropertyRange
