package CosNotification;


/**
* CosNotification/PropertyErrorSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/

public final class PropertyErrorSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotification.PropertyError value[] = null;

  public PropertyErrorSeqHolder ()
  {
  }

  public PropertyErrorSeqHolder (CosNotification.PropertyError[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotification.PropertyErrorSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotification.PropertyErrorSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotification.PropertyErrorSeqHelper.type ();
  }

}
