package CosNotification;


/**
* CosNotification/PropertySeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/

public final class PropertySeqHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotification.Property value[] = null;

  public PropertySeqHolder ()
  {
  }

  public PropertySeqHolder (CosNotification.Property[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotification.PropertySeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotification.PropertySeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotification.PropertySeqHelper.type ();
  }

}
