package CosNotification;


/**
* CosNotification/QoSAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/


// MaxEventsPerConsumer takes on a value of type long
public interface QoSAdmin extends QoSAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface QoSAdmin
