package CosNotification;


/**
* CosNotification/StopTime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/

public interface StopTime
{

  // StartTime takes a value of type TimeBase::UtcT.
  public static final String value = "StopTime";
}
