package CosNotification;


/**
* CosNotification/UnsupportedQoS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotification.idl
* Wednesday, April 19, 2017 6:31:51 PM MSK
*/

public final class UnsupportedQoS extends org.omg.CORBA.UserException
{
  public CosNotification.PropertyError qos_err[] = null;

  public UnsupportedQoS ()
  {
    super(UnsupportedQoSHelper.id());
  } // ctor

  public UnsupportedQoS (CosNotification.PropertyError[] _qos_err)
  {
    super(UnsupportedQoSHelper.id());
    qos_err = _qos_err;
  } // ctor


  public UnsupportedQoS (String $reason, CosNotification.PropertyError[] _qos_err)
  {
    super(UnsupportedQoSHelper.id() + "  " + $reason);
    qos_err = _qos_err;
  } // ctor

} // class UnsupportedQoS
